# Generated by Django 5.2 on 2025-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_percent",
                    models.PositiveBigIntegerField(
                        help_text="Enter discount as a percentage (e.g., 10 for 10%)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Leave blank for unlimited use", null=True
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
            ],
        ),
    ]
